### ISSUE TITLE
Ingest Mozilla localization corpus

### ISSUE THREAD

**Issue by kpu** [masakhane-io/masakhane-mt#127]
Tip: Mozilla has localization at https://github.com/mozilla-l10n/

There seem to be a bunch of repos for different products with different formats.  Here's an example of Standard Moroccan Tamazight:

https://github.com/mozilla-l10n/firefoxios-l10n/blob/master/zgh/firefox-ios.xliff

Or here's some Acholi:

https://github.com/mozilla-l10n/sumo-l10n/blob/master/ach/LC_MESSAGES/buddyup.po

Trying to find a nice place to just grab everything from; I've e-mailed @delphine asking for a TMX.

**Comment by Delphine** [comment]
Replied to your email, and added Jeff Beatty as a point of contact. Thanks so much for reaching out!

**Comment by kpu** [comment]
It happened thanks to Jeff Beatty!  https://opus.nlpl.eu/Mozilla-I10n.php
