### ISSUE TITLE
Update "custom test set notebook" to use language codes

### ISSUE THREAD

**Issue by cdleong** [masakhane-io/masakhane-mt#157]
https://colab.research.google.com/drive/1n_lRn6zWXDDor7scBUTnCk4x5j90LVum#scrollTo=FG5qoTCkdyCy makes it easy to generate new test sets.

**Comment by cdleong** [comment]
@juliakreutzer can you assign this to me?

**Comment by cdleong** [comment]
Made a merge request. https://github.com/masakhane-io/masakhane-mt/pull/159

**Comment by juliakreutzer** [comment]
Merged!
